from Storage import Storage
from utils import get_first_last_name


to_skip = {
    "Peter Priest II",
    "Sean Dada",
    "Ralph Scott Jr.",
    "Timothy Ferreira",
    "Khalif Havens",
    "Anthony Marecki",
    "Michael Chandler",
    "Mark Hackett",
    "Clayton Chapman",
    "Dennis Aryan",
    "Michael Sigmon",
    "Susan Hall",
    "Chris Corey",
    "Aamir Arif",
    "Richard Siegel",
    "Lea Sherman",
    "Christian Robbins",
    "Alexander Dodenhoff",
    "Paul Briscoe",
    "Antonio Alvarez",
    "Samuel Claesson",
    "Richard Mayers",
    "Gerald Heikes",
    "Steve Hill",
    "Ernest Richter",
    "Karl Ryan",
    "David Gregors",
    "Regina Liparoto",
    "Colleen Massey",
    "Bradley Horges Jr.",
    "Phillip Beachy",
    "Tiffany Ford",
    "Samuel Kravitz",
    "Jason Brown",
    "Don B. Pratt",
    "Randall Arrington",
    "Brandon James Griffin",
    "Michael Cobb Sr.",
    "Christopher Clark",
    "Andrew Gale",
    "Liz Hakola",
    "Thomas Bowman",
    "Jake Dawson",
    "Michael Downey",
    "Robert Barb",
    "Kenneth Peterson",
    "Arron Kowalski",
    "Kevin Rondeau",
    "William Harvey",
    "Sterling Sykes",
    "Ryan Donnelly",
    "Robert D'Arcy",
    "Jason Riddle",
    "Jay Mercer",
    "Gerard Beloin",
    "Andrew Black",
    "Joseph Destin",
    "Chris Mazlo",
    "Bradley Scott Wing",
    "Allen Rheinhart",
    "David Havlicek",
    "Bill Hoge",
    "Jim Blockey",
    "Anthony Frascone",
    "Jacob Soto",
    "John Delaney",
    "Christopher Gowett",
    "Brian Kenderes",
    "Liam Walker",
    "Andrew Aasen",
    "Lewis Shupe",
    "Quincy Magee",
    "Erik Messina",
    "Hussein Tartour-Aguirre",
    "Eddy Medrano",
    "Jeffrey Lemire",
    "Hastina Robinson",
    "Rufus Lopez",
    "Holland Gibson",
    "Ken Ashby",
    "Robert Reid",
    "Dustin Williams",
    "Candace Cunningham",
    "David Bozic",
    "Christopher Beckett",
    "Benjamin Rodriguez",
    "Jannie Prosser",
    "Shawn Petty",
    "Steven Cavin Sanders",
    "Athena Eastwood",
    "James Treibert",
    "Benjamin Wesley",
    "Shelby Davis",
    "Nathan Russell",
    "David Pastorius",
    "Stephen Faris",
    "Christopher Reynolds",
    "Lewie Andrews",
    "Tim Stevenski",
    "Joshua Standridge",
}


def get_candidates_without_images(db):
    missing = []
    storage = Storage()
    race_docs = db.client.collection("raceDetails").stream()
    for doc in race_docs:
        state, state_data = doc.id, doc.to_dict()
        for race_id, race_data in state_data.items():
            for candidate in race_data["candidates"].values():
                if candidate["common_name"] in to_skip:
                    continue
                first_name, last_name = get_first_last_name(candidate["common_name"])
                filename = f"{first_name.lower()}-{last_name.lower()}.webp"
                if not storage.has_image(filename):
                    missing.append(candidate["common_name"])
    return missing
