import json


def run():
    data = json.loads(
        """{
    "api_version": "1.0",
    "pagination": {
        "count": 5,
        "is_count_exact": true,
        "last_indexes": {
            "last_expenditure_date": "2024-04-10",
            "last_index": "4041120241889661053"
        },
        "pages": 1,
        "per_page": 20
    },
    "results": [
        {
            "action_code": "A",
            "action_code_full": "ADD",
            "amendment_indicator": "N",
            "amendment_number": 0,
            "back_reference_schedule_name": null,
            "back_reference_transaction_id": null,
            "candidate": {
                "candidate_id": "H4AL02162",
                "idx": 40842,
                "two_year_period": "2024"
            },
            "candidate_first_name": "ANTHONY",
            "candidate_id": "H4AL02162",
            "candidate_last_name": "DANIELS",
            "candidate_middle_name": null,
            "candidate_name": "DANIELS, ANTHONY REP.",
            "candidate_office": "H",
            "candidate_office_district": "02",
            "candidate_office_state": "AL",
            "candidate_party": "DEM",
            "candidate_prefix": "REP.",
            "candidate_suffix": null,
            "category_code": "004",
            "category_code_full": "Advertising Expenses ",
            "committee": {
                "affiliated_committee_name": "NONE",
                "candidate_ids": [],
                "city": "PALM CITY",
                "committee_id": "C00848440",
                "committee_type": "O",
                "committee_type_full": "Super PAC (Independent Expenditure-Only)",
                "cycle": 2024,
                "cycles": [
                    2024
                ],
                "cycles_has_activity": [
                    2024
                ],
                "cycles_has_financial": [
                    2024
                ],
                "designation": "U",
                "designation_full": "Unauthorized",
                "filing_frequency": "M",
                "first_f1_date": "2023-08-18",
                "first_file_date": "2023-08-18",
                "is_active": true,
                "last_cycle_has_activity": 2024,
                "last_cycle_has_financial": 2024,
                "last_f1_date": "2023-12-14",
                "last_file_date": "2024-06-08",
                "name": "PROTECT PROGRESS",
                "organization_type": null,
                "organization_type_full": null,
                "party": null,
                "party_full": null,
                "state": "FL",
                "state_full": "Florida",
                "street_1": "2740 SW MARTIN DOWNS BLVD",
                "street_2": "#51",
                "treasurer_name": "PHILIPCZYK, BRANDON",
                "zip": "34990"
            },
            "committee_id": "C00848440",
            "conduit_committee_city": null,
            "conduit_committee_id": "C00856203",
            "conduit_committee_name": null,
            "conduit_committee_state": null,
            "conduit_committee_street1": null,
            "conduit_committee_street2": null,
            "conduit_committee_zip": null,
            "dissemination_date": "2024-04-11",
            "election_type": "R2024",
            "election_type_full": "PRIMARY RUNOFF",
            "expenditure_amount": 1950.0,
            "expenditure_date": "2024-04-11",
            "expenditure_description": "IE-DANIELS-PRODUCTION RADIO ADS (ESTIMATE)",
            "file_number": 1770735,
            "filer_first_name": "BRANDON",
            "filer_last_name": "PHILIPCZYK",
            "filer_middle_name": null,
            "filer_prefix": null,
            "filer_suffix": null,
            "filing_date": "2024-04-12",
            "filing_form": "F24",
            "form_line_number": "F24-24",
            "image_number": "202404129627578946",
            "independent_sign_date": "2024-04-12",
            "independent_sign_name": "PHILIPCZYK, BRANDON",
            "is_notice": true,
            "line_number": "24",
            "link_id": 4041220241895644009,
            "memo_code": null,
            "memo_code_full": null,
            "memo_text": null,
            "memoed_subtotal": false,
            "most_recent": true,
            "notary_commission_expiration_date": null,
            "notary_sign_date": null,
            "notary_sign_name": null,
            "office_total_ytd": 908132.94,
            "original_sub_id": null,
            "payee_city": "DOVER",
            "payee_first_name": null,
            "payee_last_name": null,
            "payee_middle_name": null,
            "payee_name": "DOCKSIDE STRATEGIES",
            "payee_prefix": null,
            "payee_state": "DE",
            "payee_street_1": "8 THE GREEN",
            "payee_street_2": "STE 14712",
            "payee_suffix": null,
            "payee_zip": "19901",
            "pdf_url": "https://docquery.fec.gov/cgi-bin/fecimg/?202404129627578946",
            "previous_file_number": 1770735,
            "report_type": "24",
            "report_year": "2024",
            "schedule_type": "SE",
            "schedule_type_full": "ITEMIZED INDEPENDENT EXPENDITURES",
            "sub_id": "4041220241895686022",
            "support_oppose_indicator": "O",
            "transaction_id": "V30A821A0AFB36853248"
        },
        {
            "action_code": "A",
            "action_code_full": "ADD",
            "amendment_indicator": "N",
            "amendment_number": 0,
            "back_reference_schedule_name": null,
            "back_reference_transaction_id": null,
            "candidate": {
                "candidate_id": "H4AL02162",
                "idx": 40842,
                "two_year_period": "2024"
            },
            "candidate_first_name": "ANTHONY",
            "candidate_id": "H4AL02162",
            "candidate_last_name": "DANIELS",
            "candidate_middle_name": null,
            "candidate_name": "DANIELS, ANTHONY REP.",
            "candidate_office": "H",
            "candidate_office_district": "02",
            "candidate_office_state": "AL",
            "candidate_party": "DEM",
            "candidate_prefix": "REP.",
            "candidate_suffix": null,
            "category_code": "004",
            "category_code_full": "Advertising Expenses ",
            "committee": {
                "affiliated_committee_name": "NONE",
                "candidate_ids": [],
                "city": "PALM CITY",
                "committee_id": "C00848440",
                "committee_type": "O",
                "committee_type_full": "Super PAC (Independent Expenditure-Only)",
                "cycle": 2024,
                "cycles": [
                    2024
                ],
                "cycles_has_activity": [
                    2024
                ],
                "cycles_has_financial": [
                    2024
                ],
                "designation": "U",
                "designation_full": "Unauthorized",
                "filing_frequency": "M",
                "first_f1_date": "2023-08-18",
                "first_file_date": "2023-08-18",
                "is_active": true,
                "last_cycle_has_activity": 2024,
                "last_cycle_has_financial": 2024,
                "last_f1_date": "2023-12-14",
                "last_file_date": "2024-06-08",
                "name": "PROTECT PROGRESS",
                "organization_type": null,
                "organization_type_full": null,
                "party": null,
                "party_full": null,
                "state": "FL",
                "state_full": "Florida",
                "street_1": "2740 SW MARTIN DOWNS BLVD",
                "street_2": "#51",
                "treasurer_name": "PHILIPCZYK, BRANDON",
                "zip": "34990"
            },
            "committee_id": "C00848440",
            "conduit_committee_city": null,
            "conduit_committee_id": "C00856203",
            "conduit_committee_name": null,
            "conduit_committee_state": null,
            "conduit_committee_street1": null,
            "conduit_committee_street2": null,
            "conduit_committee_zip": null,
            "dissemination_date": "2024-04-11",
            "election_type": "R2024",
            "election_type_full": "PRIMARY RUNOFF",
            "expenditure_amount": 23328.5,
            "expenditure_date": "2024-04-10",
            "expenditure_description": "IE-DANIELS-RADIO AD BUY",
            "file_number": 1770735,
            "filer_first_name": "BRANDON",
            "filer_last_name": "PHILIPCZYK",
            "filer_middle_name": null,
            "filer_prefix": null,
            "filer_suffix": null,
            "filing_date": "2024-04-12",
            "filing_form": "F24",
            "form_line_number": "F24-24",
            "image_number": "202404129627578947",
            "independent_sign_date": "2024-04-12",
            "independent_sign_name": "PHILIPCZYK, BRANDON",
            "is_notice": true,
            "line_number": "24",
            "link_id": 4041220241895644009,
            "memo_code": null,
            "memo_code_full": null,
            "memo_text": null,
            "memoed_subtotal": false,
            "most_recent": true,
            "notary_commission_expiration_date": null,
            "notary_sign_date": null,
            "notary_sign_name": null,
            "office_total_ytd": 908132.94,
            "original_sub_id": null,
            "payee_city": "CROWNSVILLE",
            "payee_first_name": null,
            "payee_last_name": null,
            "payee_middle_name": null,
            "payee_name": "TARGETED PLATFORM MEDIA LLC",
            "payee_prefix": null,
            "payee_state": "MD",
            "payee_street_1": "P.O. BOX 237",
            "payee_street_2": null,
            "payee_suffix": null,
            "payee_zip": "210320237",
            "pdf_url": "https://docquery.fec.gov/cgi-bin/fecimg/?202404129627578947",
            "previous_file_number": 1770735,
            "report_type": "24",
            "report_year": "2024",
            "schedule_type": "SE",
            "schedule_type_full": "ITEMIZED INDEPENDENT EXPENDITURES",
            "sub_id": "4041220241895686024",
            "support_oppose_indicator": "O",
            "transaction_id": "V2B25F262753460C6013"
        },
        {
            "action_code": "A",
            "action_code_full": "ADD",
            "amendment_indicator": "N",
            "amendment_number": 0,
            "back_reference_schedule_name": null,
            "back_reference_transaction_id": null,
            "candidate": {
                "candidate_id": "H4AL02162",
                "idx": 40842,
                "two_year_period": "2024"
            },
            "candidate_first_name": "ANTHONY",
            "candidate_id": "H4AL02162",
            "candidate_last_name": "DANIELS",
            "candidate_middle_name": null,
            "candidate_name": "DANIELS, ANTHONY REP.",
            "candidate_office": "H",
            "candidate_office_district": "02",
            "candidate_office_state": "AL",
            "candidate_party": "DEM",
            "candidate_prefix": "REP.",
            "candidate_suffix": null,
            "category_code": "004",
            "category_code_full": "Advertising Expenses ",
            "committee": {
                "affiliated_committee_name": "NONE",
                "candidate_ids": [],
                "city": "PALM CITY",
                "committee_id": "C00848440",
                "committee_type": "O",
                "committee_type_full": "Super PAC (Independent Expenditure-Only)",
                "cycle": 2024,
                "cycles": [
                    2024
                ],
                "cycles_has_activity": [
                    2024
                ],
                "cycles_has_financial": [
                    2024
                ],
                "designation": "U",
                "designation_full": "Unauthorized",
                "filing_frequency": "M",
                "first_f1_date": "2023-08-18",
                "first_file_date": "2023-08-18",
                "is_active": true,
                "last_cycle_has_activity": 2024,
                "last_cycle_has_financial": 2024,
                "last_f1_date": "2023-12-14",
                "last_file_date": "2024-06-08",
                "name": "PROTECT PROGRESS",
                "organization_type": null,
                "organization_type_full": null,
                "party": null,
                "party_full": null,
                "state": "FL",
                "state_full": "Florida",
                "street_1": "2740 SW MARTIN DOWNS BLVD",
                "street_2": "#51",
                "treasurer_name": "PHILIPCZYK, BRANDON",
                "zip": "34990"
            },
            "committee_id": "C00848440",
            "conduit_committee_city": null,
            "conduit_committee_id": "C00856203",
            "conduit_committee_name": null,
            "conduit_committee_state": null,
            "conduit_committee_street1": null,
            "conduit_committee_street2": null,
            "conduit_committee_zip": null,
            "dissemination_date": "2024-04-11",
            "election_type": "R2024",
            "election_type_full": "PRIMARY RUNOFF",
            "expenditure_amount": 182224.0,
            "expenditure_date": "2024-04-10",
            "expenditure_description": "IE-DANIELS-TELEVISION AD BUY",
            "file_number": 1770735,
            "filer_first_name": "BRANDON",
            "filer_last_name": "PHILIPCZYK",
            "filer_middle_name": null,
            "filer_prefix": null,
            "filer_suffix": null,
            "filing_date": "2024-04-12",
            "filing_form": "F24",
            "form_line_number": "F24-24",
            "image_number": "202404129627578946",
            "independent_sign_date": "2024-04-12",
            "independent_sign_name": "PHILIPCZYK, BRANDON",
            "is_notice": true,
            "line_number": "24",
            "link_id": 4041220241895644009,
            "memo_code": null,
            "memo_code_full": null,
            "memo_text": null,
            "memoed_subtotal": false,
            "most_recent": true,
            "notary_commission_expiration_date": null,
            "notary_sign_date": null,
            "notary_sign_name": null,
            "office_total_ytd": 908132.94,
            "original_sub_id": null,
            "payee_city": "CROWNSVILLE",
            "payee_first_name": null,
            "payee_last_name": null,
            "payee_middle_name": null,
            "payee_name": "TARGETED PLATFORM MEDIA LLC",
            "payee_prefix": null,
            "payee_state": "MD",
            "payee_street_1": "P.O. BOX 237",
            "payee_street_2": null,
            "payee_suffix": null,
            "payee_zip": "210320237",
            "pdf_url": "https://docquery.fec.gov/cgi-bin/fecimg/?202404129627578946",
            "previous_file_number": 1770735,
            "report_type": "24",
            "report_year": "2024",
            "schedule_type": "SE",
            "schedule_type_full": "ITEMIZED INDEPENDENT EXPENDITURES",
            "sub_id": "4041220241895686023",
            "support_oppose_indicator": "O",
            "transaction_id": "VBC6E8D8C042B45342BD"
        },
        {
            "action_code": "A",
            "action_code_full": "ADD",
            "amendment_indicator": "N",
            "amendment_number": 0,
            "back_reference_schedule_name": null,
            "back_reference_transaction_id": null,
            "candidate": {
                "candidate_id": "H4AL02162",
                "idx": 40842,
                "two_year_period": "2024"
            },
            "candidate_first_name": "ANTHONY",
            "candidate_id": "H4AL02162",
            "candidate_last_name": "DANIELS",
            "candidate_middle_name": null,
            "candidate_name": "DANIELS, ANTHONY REP.",
            "candidate_office": "H",
            "candidate_office_district": "02",
            "candidate_office_state": "AL",
            "candidate_party": "DEM",
            "candidate_prefix": "REP.",
            "candidate_suffix": null,
            "category_code": "004",
            "category_code_full": "Advertising Expenses ",
            "committee": {
                "affiliated_committee_name": "NONE",
                "candidate_ids": [],
                "city": "PALM CITY",
                "committee_id": "C00848440",
                "committee_type": "O",
                "committee_type_full": "Super PAC (Independent Expenditure-Only)",
                "cycle": 2024,
                "cycles": [
                    2024
                ],
                "cycles_has_activity": [
                    2024
                ],
                "cycles_has_financial": [
                    2024
                ],
                "designation": "U",
                "designation_full": "Unauthorized",
                "filing_frequency": "M",
                "first_f1_date": "2023-08-18",
                "first_file_date": "2023-08-18",
                "is_active": true,
                "last_cycle_has_activity": 2024,
                "last_cycle_has_financial": 2024,
                "last_f1_date": "2023-12-14",
                "last_file_date": "2024-06-08",
                "name": "PROTECT PROGRESS",
                "organization_type": null,
                "organization_type_full": null,
                "party": null,
                "party_full": null,
                "state": "FL",
                "state_full": "Florida",
                "street_1": "2740 SW MARTIN DOWNS BLVD",
                "street_2": "#51",
                "treasurer_name": "PHILIPCZYK, BRANDON",
                "zip": "34990"
            },
            "committee_id": "C00848440",
            "conduit_committee_city": null,
            "conduit_committee_id": "C00856203",
            "conduit_committee_name": null,
            "conduit_committee_state": null,
            "conduit_committee_street1": null,
            "conduit_committee_street2": null,
            "conduit_committee_zip": null,
            "dissemination_date": "2024-04-10",
            "election_type": "R2024",
            "election_type_full": "PRIMARY RUNOFF",
            "expenditure_amount": 20211.0,
            "expenditure_date": "2024-04-10",
            "expenditure_description": "IE-DANIELS-DIGITAL MEDIA BUY",
            "file_number": 1769901,
            "filer_first_name": "BRANDON",
            "filer_last_name": "PHILIPCZYK",
            "filer_middle_name": null,
            "filer_prefix": null,
            "filer_suffix": null,
            "filing_date": "2024-04-11",
            "filing_form": "F24",
            "form_line_number": "F24-24",
            "image_number": "202404119627530942",
            "independent_sign_date": "2024-04-11",
            "independent_sign_name": "PHILIPCZYK, BRANDON",
            "is_notice": true,
            "line_number": "24",
            "link_id": 4041120241889007004,
            "memo_code": null,
            "memo_code_full": null,
            "memo_text": null,
            "memoed_subtotal": false,
            "most_recent": true,
            "notary_commission_expiration_date": null,
            "notary_sign_date": null,
            "notary_sign_name": null,
            "office_total_ytd": 687018.94,
            "original_sub_id": null,
            "payee_city": "CROWNSVILLE",
            "payee_first_name": null,
            "payee_last_name": null,
            "payee_middle_name": null,
            "payee_name": "TARGETED PLATFORM MEDIA LLC",
            "payee_prefix": null,
            "payee_state": "MD",
            "payee_street_1": "P.O. BOX 237",
            "payee_street_2": null,
            "payee_suffix": null,
            "payee_zip": "210320237",
            "pdf_url": "https://docquery.fec.gov/cgi-bin/fecimg/?202404119627530942",
            "previous_file_number": 1769901,
            "report_type": "24",
            "report_year": "2024",
            "schedule_type": "SE",
            "schedule_type_full": "ITEMIZED INDEPENDENT EXPENDITURES",
            "sub_id": "4041120241889661054",
            "support_oppose_indicator": "O",
            "transaction_id": "V9C1AB3CF761DC858B30"
        },
        {
            "action_code": "A",
            "action_code_full": "ADD",
            "amendment_indicator": "N",
            "amendment_number": 0,
            "back_reference_schedule_name": null,
            "back_reference_transaction_id": null,
            "candidate": {
                "candidate_id": "H4AL02162",
                "idx": 40842,
                "two_year_period": "2024"
            },
            "candidate_first_name": "ANTHONY",
            "candidate_id": "H4AL02162",
            "candidate_last_name": "DANIELS",
            "candidate_middle_name": null,
            "candidate_name": "DANIELS, ANTHONY REP.",
            "candidate_office": "H",
            "candidate_office_district": "02",
            "candidate_office_state": "AL",
            "candidate_party": "DEM",
            "candidate_prefix": "REP.",
            "candidate_suffix": null,
            "category_code": "004",
            "category_code_full": "Advertising Expenses ",
            "committee": {
                "affiliated_committee_name": "NONE",
                "candidate_ids": [],
                "city": "PALM CITY",
                "committee_id": "C00848440",
                "committee_type": "O",
                "committee_type_full": "Super PAC (Independent Expenditure-Only)",
                "cycle": 2024,
                "cycles": [
                    2024
                ],
                "cycles_has_activity": [
                    2024
                ],
                "cycles_has_financial": [
                    2024
                ],
                "designation": "U",
                "designation_full": "Unauthorized",
                "filing_frequency": "M",
                "first_f1_date": "2023-08-18",
                "first_file_date": "2023-08-18",
                "is_active": true,
                "last_cycle_has_activity": 2024,
                "last_cycle_has_financial": 2024,
                "last_f1_date": "2023-12-14",
                "last_file_date": "2024-06-08",
                "name": "PROTECT PROGRESS",
                "organization_type": null,
                "organization_type_full": null,
                "party": null,
                "party_full": null,
                "state": "FL",
                "state_full": "Florida",
                "street_1": "2740 SW MARTIN DOWNS BLVD",
                "street_2": "#51",
                "treasurer_name": "PHILIPCZYK, BRANDON",
                "zip": "34990"
            },
            "committee_id": "C00848440",
            "conduit_committee_city": null,
            "conduit_committee_id": "C00856203",
            "conduit_committee_name": null,
            "conduit_committee_state": null,
            "conduit_committee_street1": null,
            "conduit_committee_street2": null,
            "conduit_committee_zip": null,
            "dissemination_date": "2024-04-10",
            "election_type": "R2024",
            "election_type_full": "PRIMARY RUNOFF",
            "expenditure_amount": 12000.0,
            "expenditure_date": "2024-04-10",
            "expenditure_description": "IE - DANIELS - DIGITAL MEDIA PRODUCTION (ESTIMATE)",
            "file_number": 1769901,
            "filer_first_name": "BRANDON",
            "filer_last_name": "PHILIPCZYK",
            "filer_middle_name": null,
            "filer_prefix": null,
            "filer_suffix": null,
            "filing_date": "2024-04-11",
            "filing_form": "F24",
            "form_line_number": "F24-24",
            "image_number": "202404119627530942",
            "independent_sign_date": "2024-04-11",
            "independent_sign_name": "PHILIPCZYK, BRANDON",
            "is_notice": true,
            "line_number": "24",
            "link_id": 4041120241889007004,
            "memo_code": null,
            "memo_code_full": null,
            "memo_text": null,
            "memoed_subtotal": false,
            "most_recent": true,
            "notary_commission_expiration_date": null,
            "notary_sign_date": null,
            "notary_sign_name": null,
            "office_total_ytd": 687018.94,
            "original_sub_id": null,
            "payee_city": "DOVER",
            "payee_first_name": null,
            "payee_last_name": null,
            "payee_middle_name": null,
            "payee_name": "DOCKSIDE STRATEGIES",
            "payee_prefix": null,
            "payee_state": "DE",
            "payee_street_1": "8 THE GREEN",
            "payee_street_2": "STE 14712",
            "payee_suffix": null,
            "payee_zip": "19901",
            "pdf_url": "https://docquery.fec.gov/cgi-bin/fecimg/?202404119627530942",
            "previous_file_number": 1769901,
            "report_type": "24",
            "report_year": "2024",
            "schedule_type": "SE",
            "schedule_type_full": "ITEMIZED INDEPENDENT EXPENDITURES",
            "sub_id": "4041120241889661053",
            "support_oppose_indicator": "O",
            "transaction_id": "V32587B00B2DC75BD7FB"
        }
    ]
}"""
    )

    amounts = []
    for exp in data["results"]:
        amounts.append(exp["expenditure_amount"])
    print(amounts)
    print(sum(amounts))


if __name__ == "__main__":
    run()
